spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/sweet?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username : root
    password : 123$%^
    # password : ENC(51uMJKgSnH+mihXyFLSM+vRrz+pJptXJ)
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    generate-unique-name: false
    cache-prep-stmts: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 6000
        max-idle: 8
        min-idle: 0
    timeout: 500
  jpa:
    open-in-view: false
  cache:
    type: redis
  session:
    store-type: redis
  mvc:
    view:
      prefix: /blog/
      suffix: .html
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path:

mybatis:
  type-aliases-package: com.song.sweet.model
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

jasypt:
  encryptor:
    stringOutputType: base64
    algorithm: PBEWithMD5AndDES
    poolSize: 1
    provider-name:
    provider-class-name:
    keyObtentionIterations: 1000
    ivGeneratorClassname: org.jasypt.salt.NoOpIVGenerator
    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
    password: a6d11ff4814488830abf582144cb5df3

logging:
  level:
    com:
      song:
        sweet:
          dao: debug
#    org:
#      springframework:
#        web: trace

gaode:
  map:
    api.key: 55a2c0fbef6fc7e5f5d9c40cf14536d1
    api.url: https://restapi.amap.com/v3/ip

chinaz:
  api:
    key: d8a0c7ef0f124724ac8c34381a6af116
    url: http://apidata.chinaz.com/CallAPI/Ip