spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/sweet_girl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username : ENC(7Y1ASPSRVRnIsluHgSMFrw==)
    password : ENC(zr1CAapZa43EhtHzHY03pQ==)
#    password : ENC(51uMJKgSnH+mihXyFLSM+vRrz+pJptXJ)
    generate-unique-name: false
    cache-prep-stmts: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: jmad252666
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000
  cache:
    type: redis
  session:
    store-type: redis
  mvc:
    view:
      prefix: /blog/
      suffix: .html
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path:

mybatis:
  type-aliases-package: com.song.sweetgirl.model
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

jasypt:
  encryptor:
    string-output-type: base64
    algorithm: PBEWithMD5AndDES
    pool-size: 1
    keyObtentionIterations: 1000
    provider-name:
    provider-class-name:
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.salt.NoOpIVGenerator
    password: YlhsemNXdyUzRA==

logging:
  level:
    com.song.sweetgirl.dao: debug