server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    username : root
    password :
    generate-unique-name: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    cache-prep-stmts: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000
  cache:
    type: redis
  session:
    store-type: redis
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis:
  type-aliases-package: com.song.sweetgirl.model
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.song.sweetgirl.dao: debug